### ISSUE TITLE
Can Aho-Corasick be used for finding characters in keywords?

### ISSUE THREAD

**Issue by deadcoder0904** [BlackGlory/aho-corasick#1]
Basically, I want an emoji library to fuzzy-match based on keywords as I'm pressing them.

This is the relevant issue -> https://github.com/chapmankyle/emoji-set/issues/6

Can this library be used for it?

**Comment by BlackGlory** [comment]
If you don't need typo tolerance, yes, it can.

**Comment by BlackGlory** [comment]
The purpose of the emoji-set library seems to be search rather than matching, I suggest you use an inverted index or Trie library instead of a matching library, like [Flexsearch](https://github.com/nextapps-de/flexsearch).

**Comment by deadcoder0904** [comment]
@BlackGlory I think I need typo tolerance for emojis. Basically, I want it to work like Slack.

What is the difference between search & matching? Because as I can see, I need to search for an emoji using a keyword & then it must match it so it does both. I guess you mean search like Google Search & by match you mean it to be like [F5Bot](https://f5bot.com/) which matches keywords out of Reddit. It also uses Aho-Corasick in PHP.

**Comment by BlackGlory** [comment]
@deadcoder0904 The purpose of libraries like Fastscan and Aho-Corasick is to "check whether a user-submitted string matches one or more patterns", and it compiles an automaton to include these patterns. Whenever a new pattern needs to be added, the automaton needs to be recompiled. You can think of it as a regular expression engine with fewer features, but with excellent performance when there are a lot of patterns. The reason it is not suitable for emoji-set is that the matching will only work if the user-submitted string is longer than the pattern.

What you need is actually "autocomplete"(Trie) or "full-text search"(Inverted index). Explaining them can be complicated, I suggest you read Wikipedia.

**Comment by deadcoder0904** [comment]
Excellent, thank you! I got it 🎉 

I'll read about Trie & Inverted Index :)
